name: CI to Docker hub 

on:
  push:
    branches: [ main ]
# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Extract Version
        id: version_step
        run: echo "##[set-output name=version;]VERSION=${GITHUB_REF#$"refs/tags/v"}"

      - name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: | 
            ${{ secrets.DOCKER_HUB_USERNAME }}/opencv-dlib:${{steps.version_step.outputs.version}}
            ${{ secrets.DOCKER_HUB_USERNAME }}/opencv-dlib:latest
